"""empty message

Revision ID: 8aebdd5f279a
Revises: 
Create Date: 2021-10-26 17:28:48.916930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aebdd5f279a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoapp', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todoapp SET completed=false WHERE completed IS NULL')
    op.alter_column('todoapp', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todoapp', 'completed')
    # ### end Alembic commands ###
